### ISSUE TITLE
App crashes when deployed to iPhone 6 - fails to read survey

### ISSUE THREAD

**Issue by colingor** [edina/crowdsurvey#21]
When the app launches on a physical device, the Alamofire request to get the survey json never seems to complete - the code never enters the completion callback for some reason. As a result, it attempts to unwrap a nil survey object and crashes.

**Comment by ianfieldhouse** [comment]
This is caused by the fact that the iPhone is on Eduroam and so can't access dlib-rainbow on port 3000. In the meantime we should revert the url that we use in development to Ruben's Gist so that we can test on device. We should also get a proxy entry created by infrastructure or on dlib-rainbow so that we can access the Loopback API via port 80.
